name: Go
description: GitHub Actions for building and testing Go projects

inputs:
  project-path:
    type: string
    required: false
    default: ''
  go-version:
    type: string
    required: false
    default: '1.20'
  golang-ci-lint-version:
    type: string
    required: false
    default: 'v1.52.2'
  golang-ci-lint-args:
    type: string
    required: false
    default: '--timeout=10m'
  skip-lint:
    type: boolean
    required: false
    default: false
  skip-build:
    type: boolean
    required: false
    default: false
  skip-test:
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Change to project directory
      env:
        PROJECT_PATH: ${{ inputs.project-path }}
      run: cd "${PROJECT_PATH}"
      shell: bash

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run golangci-lint
      if: inputs.skip-lint == 'false'
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ inputs.golang-ci-lint-version }}
        args: ${{ inputs.golang-ci-lint-args }}

    - name: Skip running golangci-lint
      if: inputs.skip-lint == 'true'
      run: echo "Skipped running golangci-lint"
      shell: bash

    - name: Build
      if: inputs.skip-build == 'false'
      run: go build -v ./...
      shell: bash

    - name: Skip building
      if: inputs.skip-build == 'true'
      run: echo "Skipped building"
      shell: bash

    - name: Test
      if: inputs.skip-test == 'false'
      run: go test -v ./...
      shell: bash

    - name: Skip testing
      if: inputs.skip-test == 'true'
      run: echo "Skipped testing"
      shell: bash
